title = "The DataThings Blog"
baseurl = "http://datathings.com/blog/"
canonifyURLs = true
languageCode = "en-us"
theme = "hugo-cactus-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-92108122-1"
# Disable comments by leaving disqusShortname empty
disqusShortname = ""
publishDir = "public/blog"
[social]
    twitter  = "https://twitter.com/datathingslu"

[taxonomies]
    category = "categories"
    tag = "tags"
