baseurl = "http://datathings.com/blog/"
languageCode = "en-us"
title = "Datathings Blog"
theme = "hugo-strata-theme"
disqusShortname = "datathings"
googleAnalytics = "UA-92108122-1"
paginate = 10
publishDir = "public/blog"

[params]
	name = "DataThings"
	description = "The Datathings Blog: we speak about live data Analytics, machine learning, neural networks, temporal graph databases, modeling, big data."
	date_format = "02-01-2006"
	# Add custom assets with their paths relative to the static folder
	custom_js   = []
	custom_css  = []
	[params.sidebar]
		# Replace the avatar with a picture of your own under static/images
		avatar = "dt_logo_square.svg"
		# Use Markdown to format the string. This works nearly all over the theme
		bio = "This is **DataThings'** blog,<br />here we share innovations about<br />live data analytics, machine learning,<br />neural networks, temporal graph<br /> databases, big data."
		# The icons will be shown if you enter your username
		twitter = "datathingslu"
		github = "datathings"
		gitlab = ""
		dribbble = ""
		# facebook = "datathingslu"
		# googleplus = "datathings"
		flickr = ""
		linkedin = "https://www.linkedin.com/company/datathings"
		copyright = [
			"DataThings &copy; 2017"
		]

	[params.about]
		hide  = false
		title = "We are DataThings"
		content = "We are a startup of four passionate researchers holding PhDs in Computer Science. After several years of successful collaboration at the University of Luxembourg/SnT, we founded DataThings to start the next chapter in live data analytics. We aim at improving live analytics over complex and time-evolving data in order to support your businesses in operational decision-making. Please visit <a href=\"https://www.datathings.com\">our website</a> to find out more"


	[params.portfolio]
		hide  = true
		title = "Recent Work"

		# The images and thumbnails are stored under static/images
		# Create and change subfolders as you like
		[[params.portfolio.gallery]]
			image = "fulls/01.jpg"
			thumb = "thumbs/01.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/02.jpg"
			thumb = "thumbs/02.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/03.jpg"
			thumb = "thumbs/03.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/04.jpg"
			thumb = "thumbs/04.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/05.jpg"
			thumb = "thumbs/05.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

		[[params.portfolio.gallery]]
			image = "fulls/06.jpg"
			thumb = "thumbs/06.jpg"
			title = "Lorem ipsum dolor."
			description = "Lorem ipsum dolor sit amet."

	[params.recentposts]
		hide  = false
		title = "Recent blog posts"

	[params.contact]
		hide  = true
		title = "Get In Touch"
		content = "Accumsan pellentesque commodo blandit enim arcu non at amet id arcu magna. Accumsan orci faucibus id eu lorem semper nunc nisi lorem vulputate lorem neque lorem ipsum dolor."

		address = [
			"1234 Somewhere Rd.",
			"Nashville, TN 00000",
			"United States"
		]
		phone = "000-000-0000"

		# Since this template is static, the contact form uses www.formspree.io as a
		# proxy. The form makes a POST request to their servers to send the actual
		# email. Visitors can send up to a 1000 emails each month for free.
	    #
	    # What you need to do for the setup?
	    #
	    # - set your email address under 'email' below
	    # - upload the generated site to your server
	    # - send a dummy email yourself to confirm your account
	    # - click the confirm link in the email from www.formspree.io
	    # - you're done. Happy mailing!
		email = "hello@example.com"

		[params.contact.form]
			# Set custom strings for the form if your native
			# language isn't English
			name = "Name"
			email = "Email"
			message = "Message"
			submit = "Send message"


# Menu links that appear on the left sidebar


[[menu.main]]
	name = "Home"
	url  = "/"
	weight = 0

[[menu.main]]
	name = "All posts"
	url  = "post/"
	weight = 10

[[menu.main]]
		name = "Website"
		url  = "http://www.datathings.com"
		weight = 20
