title = "The DataThings Blog"
baseurl = "http://datathings.com/blog/"
canonifyURLs = true
languageCode = "en-us"
RSSLink ="datathingsRSS.xml"
theme = "hugo-cactus-theme"
#theme = "hugo-dgraph-theme"
# Enter your tracking code to enable Google Analytics
googleAnalytics = "UA-92108122-1"
# Disable comments by leaving disqusShortname empty


[taxonomies]
    category = "categories"
    tag = "tags"


# Number of blogs you want to list on a single page.
paginate = 5
paginatePath  ="page"

    [params]

      name = "The DataThings Blog"
      bio = "A blog about data Analytics, machine learning, temporal graph databases, modeling, big data. The blog is edited by the DataThings crew members."
      enableRSS = true
      subscribe = "RSS feed"
      # To integrate discourse commenting system and also to display discourse in the footer.
      #discourse = ""

      # The path of the repo excluding https://github.com. This would work only for public repos. It is used for displaying stars for the repo.
      github = "datathings/greycat"

      # Website url, used to have a link in the footer as well as on the top.
      website = "www.datathings.com"

      # Twitter handle for sharing the post via
      twitter = "datathingslu"

      # Website demo url, used on the top.
      #demo = "https://dgraph.io"

      # Wiki url, used to have a link in the footer.
      #wiki = "https://wiki.dgraph.io/"

      # Slack url, used to have a link in the footer.
      #slack = "https://slack.dgraph.io/"

      # Angel list startup profile name, used to have a link in the footer.
      #angellist = "dgraph-labs"

    copyright = "Copyright © 2017, DataThings S.a.r.l all rights reserved."
